version: '3.8'

services:
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.local              
    volumes:
      - ./src/backend:/app
      - podcast_cache:/app/cache
    restart: unless-stopped
    
volumes:
  podcast_cache: